### ISSUE TITLE
Añadir reproductor de música y música

### ISSUE THREAD

**Issue by dipzza** [clubbrocoli/pld-practicas#33]
Debería ser una instancia global para reproducir la música en paralelo y así que no se corte al cambiar entre escenas ni tener que añadir un reproductor de música en cada escena. 

Estaría guay ya que estamos añadir a las opciones del juego un control del volumen.

**Comment by juanheliosg** [comment]
Voy poniendo temas aquí que me molan:

Rollito cyberpunk pero sin pasarse, el tema respira y no es demasiado machacon https://opengameart.org/content/driving-game-stylish-retro-beat

Tema bastante divertido y encaja tmb a nivel de ritmo https://opengameart.org/content/jump-higher-run-faster-jump-run-miniboss-mix

Chiptune guapo https://opengameart.org/content/8-bit-chiptune-you-cant-stop-the-disco

Chiputune rápido/agresivo pero también con toquecito de picardia que creo que es lo que buscamos https://opengameart.org/content/fast-level-loop-8-bit-chiptune

**Comment by dipzza** [comment]
Busy day at the market: https://opengameart.org/content/busy-day-at-the-market

**Comment by dipzza** [comment]
Me gustan mucho todas las que pusiste, pegan un montón
